name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64
          check-latest: false

      - name: Download and set up Android SDK
        run: |
          # 下载并解压 Android SDK 命令行工具
          mkdir -p $HOME/Android/Sdk/cmdline-tools
          cd $HOME/Android/Sdk/cmdline-tools
          curl -O https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
          unzip commandlinetools-linux-7583922_latest.zip
          rm commandlinetools-linux-7583922_latest.zip
          
          # 创建链接，确保 sdkmanager 使用最新的路径
          ln -s $HOME/Android/Sdk/cmdline-tools/latest $HOME/Android/Sdk/cmdline-tools/default

          # 设置 ANDROID_HOME 环境变量
          echo "ANDROID_HOME=$HOME/Android/Sdk" >> $GITHUB_ENV
          echo "PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_ENV
          
          # 导出 ANDROID_HOME 环境变量到当前 shell 会话
          export ANDROID_HOME=$HOME/Android/Sdk
          export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin

      - name: Install SDK packages
        run: |
          # 使用 sdkmanager 安装 SDK 平台和构建工具
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-33" "build-tools;30.0.3"

      - name: Create local.properties file
        run: echo "sdk.dir=$HOME/Android/Sdk" > local.properties

      - name: Build APK
        run: ./gradlew clean assembleRelease
