name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'
    - name: Set up Android SDK
      uses: reactivecircus/android-sdk@v1
      with:
        api-level: 29 # This sets Android API level to 29 (Android 10)
        build-tools-version: '30.0.3' # Ensure compatibility with the tools you are using
    - name: Build APK with Gradle
      run: ./gradlew assembleRelease
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: MyAPK
        path: app/build/outputs/apk/release/*.apk
