name: Android CI

on:
  workflow_dispatch:  # 手动触发
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout code

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'  # 使用 Java 17
        distribution: 'temurin'  # 使用 Eclipse Temurin 发行版

    # 更新 Gradle 到 v8.11
    - name: Set up Gradle 8.11
      run: |
        wget https://services.gradle.org/distributions/gradle-8.11-bin.zip
        unzip gradle-8.11-bin.zip -d /opt/gradle
        sudo ln -s /opt/gradle/gradle-8.11/bin/gradle /usr/local/bin/gradle

    # 安装 Android SDK 和 NDK
    - name: Install Android SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
        unzip commandlinetools-linux-7583922_latest.zip -d $HOME/android-sdk
        echo "y" | $HOME/android-sdk/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/android-sdk "platform-tools" "build-tools;30.0.3" "platforms;android-29"
        export ANDROID_HOME=$HOME/android-sdk
        export PATH=$ANDROID_HOME/cmdline-tools/bin:$ANDROID_HOME/platform-tools:$PATH
        echo "org.gradle.jvmargs=-Xmx4g" >> gradle.properties

    - name: Build APK with Gradle
      run: |
        git clone https://github.com/3582730951/MiKernelApp.git MiKernelApp
        chmod -R 777 MiKernelApp
        cd MiKernelApp
        ./gradlew dependencies
        ./gradlew assembleRelease --stacktrace

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: MyAPK
        path: ./MiKernelApp/app/build/outputs/apk/release/*.apk
