name: Android CI

on:
  workflow_dispatch:  # 手动触发
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout code

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    # 手动安装 Android SDK
    - name: Install Android SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
        unzip commandlinetools-linux-7583922_latest.zip -d $HOME/android-sdk
        # 这里修正解压后路径问题，确保 sdkmanager 可以找到
        mkdir -p $HOME/android-sdk/cmdline-tools
        mv $HOME/android-sdk/tools $HOME/android-sdk/cmdline-tools
        echo "y" | $HOME/android-sdk/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/android-sdk "platform-tools" "build-tools;30.0.3" "platforms;android-29"
        export ANDROID_HOME=$HOME/android-sdk
        export PATH=$ANDROID_HOME/cmdline-tools/bin:$ANDROID_HOME/platform-tools:$PATH

    - name: Build APK with Gradle
      run: ./MiKernelApp/gradlew assembleRelease

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: MyAPK
        path: ./MiKernelApp/app/build/outputs/apk/release/*.apk
