name: Android CI

on:
  workflow_dispatch:  # 手动触发
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 使用 git clone 拉取代码
    - name: Clone repository
      run: git clone https://github.com/3582730951/MiKernelApp.git

    # 设置 JDK 环境
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    # 设置 Android SDK
    - name: Set up Android SDK
      uses: reactivecircus/android-sdk@v1
      with:
        api-level: 29  # Android 10
        build-tools-version: '30.0.3'

    # 编译 APK
    - name: Build APK with Gradle
      run: ./MiKernelApp/gradlew assembleRelease  # 根据实际路径修改

    # 上传 APK 作为构建产物
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: MyAPK
        path: ./MiKernelApp/app/build/outputs/apk/release/*.apk  # 根据实际路径修改
